### PR TITLE
Add RBAC UI

### PR DESCRIPTION
**Pull request by sylvain121**
This is an contribution of "Orange Business Service" to the RBAC UI: 

- New Management item entry in menu
- A new Interface with users, groups, roles and permissions management.

Thanks

### CODE REVIEW

**Comment by grossmj** [comment]
@sylvain121 does this include the JWT token refresh support?

**Comment by sylvain121** [comment]
@grossmj  No, @piotrpekala7 have add a previously a LoginGuard which do the functionality.

**Comment by grossmj** [comment]
@sylvain121 do you plan to add more to this PR? is it ready for review? thanks

**Comment by sylvain121** [comment]
hi @grossmj , this PR is ready for me. thank

**Review by piotrpekala7 — APPROVED** [review]

**Pull request merged**
