### PR TITLE
Option to fit in view

### PR DESCRIPTION
**Pull request by piotrpekala7**

### CODE REVIEW

**Comment by piotrpekala7** [comment]
@ziajka Currently scroll position is calculated correctly but we still have unexpected results

**Comment by ziajka** [comment]
What results are unexpected?

**Comment by ziajka** [comment]
Just read the comment in an email. What is the reason?

**Comment by piotrpekala7** [comment]
@ziajka That's the problem I'm not able to find the reason why https://github.com/GNS3/gns3-web-ui/pull/530/files#diff-be4611ab27a1d015c3d724d544dfe7e3R548 doesn't work properly

**Comment by ziajka** [comment]
@piotrpekala7 as discussed, try to find an event when map is rendered.

**Pull request merged**
