### PR TITLE
Upgrade to Angular 10 [high importance]

### PR DESCRIPTION
**Pull request by piotrpekala7**

### CODE REVIEW

**Comment by piotrpekala7** [comment]
After updating dependencies: Module build failed. Can't resolve '../fonts/NotoSansBoldItalic.eot'

**Comment by piotrpekala7** [comment]
Solution from https://stackoverflow.com/questions/44422046/webpack-font-cant-resolve doesn't work

**Comment by piotrpekala7** [comment]
outdatedPackages

all packages were updated to newest version except from: @types/node and notosans-fontface, these packages are incompatible with electron 9.x.x

**Comment by piotrpekala7** [comment]
because I updated the angular material on this pr it needs testing

**Comment by grossmj** [comment]
> because I updated the angular material on this pr it needs testing.

I tested by running a few projects, adding nodes and launching consoles. Looks fine to me.

There are a few conflicts to resolve and the unit tests should be fixed as well.

**Comment by piotrpekala7** [comment]
firstly I have to fix compilation warnings:

WARNING in C:\Users\piotr.pekala\Desktop\gns3-web-ui\src\test.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

WARNING in C:\Users\piotr.pekala\Desktop\gns3-web-ui\src\app\cartography\testing.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

WARNING in C:\Users\piotr.pekala\Desktop\gns3-web-ui\src\app\cartography\tool.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

WARNING in C:\Users\piotr.pekala\Desktop\gns3-web-ui\src\app\cartography\widgets\drawings.backup.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

WARNING in C:\Users\piotr.pekala\Desktop\gns3-web-ui\src\app\converters\converter.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

WARNING in C:\Users\piotr.pekala\Desktop\gns3-web-ui\src\app\models\software.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

WARNING in C:\Users\piotr.pekala\Desktop\gns3-web-ui\src\app\services\testing.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

WARNING in C:\Users\piotr.pekala\Desktop\gns3-web-ui\src\app\testing\app-testing\app-testing.module.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

WARNING in C:\Users\piotr.pekala\Desktop\gns3-web-ui\src\environments\environment.electron.prod.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

WARNING in C:\Users\piotr.pekala\Desktop\gns3-web-ui\src\environments\environment.electron.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

WARNING in C:\Users\piotr.pekala\Desktop\gns3-web-ui\src\environments\environment.github.prod.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

WARNING in C:\Users\piotr.pekala\Desktop\gns3-web-ui\src\environments\environment.prod.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

WARNING in C:\Users\piotr.pekala\Desktop\gns3-web-ui\src\app\services\node.service.ts depends on rxjs/add/operator/map. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in C:\Users\piotr.pekala\Desktop\gns3-web-ui\src\app\cartography\helpers\font-fixer.ts depends on css-tree. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in C:\Users\piotr.pekala\Desktop\gns3-web-ui\node_modules\rxjs\add\operator\map.js depends on rxjs-compat/add/operator/map. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in C:\Users\piotr.pekala\Desktop\gns3-web-ui\src\app\components\project-map\new-template-dialog\new-template-dialog.component.ts depends on uuid. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in C:\Users\piotr.pekala\Desktop\gns3-web-ui\src\app\components\project-map\project-map-menu\project-map-menu.component.ts depends on save-svg-as-png. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in C:\Users\piotr.pekala\Desktop\gns3-web-ui\src\app\components\servers\server-discovery\server-discovery.component.ts depends on rxjs/Rx. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in C:\Users\piotr.pekala\Desktop\gns3-web-ui\node_modules\rxjs\Rx.js depends on rxjs-compat. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in C:\Users\piotr.pekala\Desktop\gns3-web-ui\node_modules\angular-draggable-droppable\__ivy_ngcc__\fesm2015\angular-draggable-droppable.js depends on @mattlewis92/dom-autoscroller. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in C:\Users\piotr.pekala\Desktop\gns3-web-ui\node_modules\angular2-hotkeys\__ivy_ngcc__\fesm2015\angular2-hotkeys.js depends on mousetrap. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in C:\Users\piotr.pekala\Desktop\gns3-web-ui\node_modules\@mattlewis92\dom-autoscroller\dist\bundle.js depends on dom-plane. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in C:\Users\piotr.pekala\Desktop\gns3-web-ui\node_modules\@mattlewis92\dom-autoscroller\dist\bundle.js depends on dom-set. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

**Comment by piotrpekala7** [comment]
then I will create separate pull-request for unit tests, I didn't do that before cause I know that most of them need to be rewritten, TestBed functions are deprecated with angular 10

**Pull request merged**
