### PR TITLE
Add navigation to user management page

### PR DESCRIPTION
**Pull request by BenoitVuagnat**

### CODE REVIEW

**Comment by piotrpekala7** [comment]
please update with changes from master before merging

**Comment by grossmj** [comment]
How do you access the page?

**Comment by BenoitVuagnat** [comment]
You can access the page in the navigation menu :

image

**Comment by grossmj** [comment]
I was on the wrong branch. Now I can access it :+1:

**Review by piotrpekala7 — APPROVED** [review]

**Pull request merged**
