### PR TITLE
Integrate Google Analytics in Web UI

### PR DESCRIPTION
**Pull request by piotrpekala7**
Fix for https://github.com/GNS3/gns3-web-ui/issues/634 according to https://codeburst.io/using-google-analytics-with-angular-25c93bffaa18

### CODE REVIEW

**Comment by ziajka** [comment]
Yep, we need to listen for router events:

> /** app.component.ts **/
> ...
> constructor(private router: Router) {
>      this.router.events.subscribe(event => {
>       if (event instanceof NavigationEnd) {
>         (<any>window).ga('set', 'page', event.urlAfterRedirects);
>         (<any>window).ga('send', 'pageview');
>       }
>     });
>   }
> ...

**Comment by piotrpekala7** [comment]
@ziajka What kind of events do we want to track?

**Comment by ziajka** [comment]
Looks like putting the script into index.html doesn't guarantee SPA page views will be tracked. If understand correctly we need to attach to Router and listen on those events, then send back to GA.

**Comment by piotrpekala7** [comment]
@ziajka This code will trigger a pageview event and send it to GA so we will see active users. Extending app.component.ts captures router events. That's why I'm asking you

**Comment by piotrpekala7** [comment]
?

**Comment by ziajka** [comment]
All is good now, many thanks.

**Pull request merged**
