### PR TITLE
Add Dockerfile for development

### PR DESCRIPTION
**Pull request by nabilbendafi**
Everything is in the title :-)

Docker image and container creation tested :white_check_mark: 
```bash
$> docker build -t gns3-web-ui .
...
Successfully tagged gns3-web-ui:latest                                                                                

$> docker run -i -h gns3UIvm -p 8080:8080/tcp -t gns3-web-ui ng serve --port 8080 --host 0.0.0.0
** NG Live Development Server is listening on 0.0.0.0:8080, open your browser on http://localhost:8080/ **
 94% asset optimizationwebpack: wait until bundle finished: /                           
Date: 2018-02-21T11:20:40.825Z
Hash: 6e939dcadaca5ad3d8dc
Time: 11709ms
chunk {inline} inline.bundle.js (inline) 3.85 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 402 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 598 kB [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 674 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 18.9 MB [initial] [rendered]

webpack: Compiled successfully.
```

### CODE REVIEW

**Comment by ziajka** [comment]
Hi @nabilbendafi,
Thanks for the PR!
Could you replace `npm` with `yarn`? Basically it's preferred packing system. 

We're open source software and we need to keep proper licensing. If you may please familiarize with:

https://github.com/GNS3/gns3-server/blob/master/CONTRIBUTING.md
and 
https://github.com/GNS3/cla

Thank you very much.
Cheers,
Dominik

**Comment by nabilbendafi** [comment]
CLA signed https://github.com/GNS3/cla/pull/11

**Comment by ziajka** [comment]
Thanks @nabilbendafi! if you may then just make a Dockerfile based on yarn. You can do that by switching to the branch of this PR and make another commit.
Cheers,
Dominik

**Comment by nabilbendafi** [comment]
OK, I need first to check that it's running well before amending my changes.

**Comment by ziajka** [comment]
Super!

**Comment by nabilbendafi** [comment]
It looks like it's properly now moved to `yarn` 
```bash
Your global Angular CLI version (1.7.1) is greater than your local
version (1.6.5). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".
** NG Live Development Server is listening on 0.0.0.0:8080, open your browser on http://localhost:8080/ **
Date: 2018-02-22T11:05:20.102Z                                                           
Hash: 27b41a63a28d3ce59d3b
Time: 13960ms
chunk {inline} inline.bundle.js (inline) 5.79 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 416 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 600 kB [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 699 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 18.7 MB [initial] [rendered]

webpack: Compiled successfully.
```

**Pull request merged**
