### PR TITLE
Master 3.0, add privileges to role management

### PR DESCRIPTION
**Pull request by sylvain121**
This PR:
Remove old permission's system management and code references.
Add privileges management to role

### CODE REVIEW

**Comment by grossmj** [comment]
Thanks for the PR :)

I spotted one issue so far.

Screenshot from 2023-09-19 17-55-37

Clicking on a group produces an 404 error because `/access/groups/{user_group_id}/roles` doesn't exist, groups are associated with a role when a new ACE is created.

**Comment by grossmj** [comment]
> Remove old permission's system management and code references.
Add privileges management to role

Just noticed that groups haven't been modified yet. Should I just merge this PR and the rest will come in other PRs?

**Comment by grossmj** [comment]
This is the SQL model for the RBAC system, though this may help you to see how things are related to each other.

Screenshot from 2023-09-19 18-06-18

**Comment by sylvain121** [comment]
Hi, 
Yes, updated Groups management and ACLs will be submitted in next PRs.
You can merge it, or wait for others PRs coming this week.

**Pull request merged**
