### PR TITLE
Enhancement/1354

### PR DESCRIPTION
**Pull request by rajnikantsolarwinds**

### CODE REVIEW

**Comment by grossmj** [comment]
This dialog is displayed when 'saving as' a project, this is not exporting a project:

Screenshot from 2022-07-20 00-23-05

This dialog should be displayed instead:

Screenshot from 2022-07-20 00-22-47

The dialog when deleting projects should say mention "projects", not "files".

Screenshot from 2022-07-20 00-30-15

**Comment by grossmj** [comment]
After the merge, I noticed a problem with the top-right menu.

Once you click on Help or Settings

Screenshot from 2022-07-23 10-56-01

You cannot go to other entries in that menu. Looks like `controllerId` is lost by going to Help or Settings.

Screenshot from 2022-07-23 10-56-12

**Comment by rajnikantsolarwinds** [comment]
> After the merge, I noticed a problem with the top-right menu.
> 
> Once you click on Help or Settings
> 
> Screenshot from 2022-07-23 10-56-01
> 
> You cannot go to other entries in that menu. Looks like `controllerId` is lost by going to Help or Settings.
> 
> Screenshot from 2022-07-23 10-56-12

@grossmj , 
It was the component url/routing issues,
 So I have resolve this issue by modifies the URL/Routings of the   components (Help and  Settings).
`help => controller/:controller_id/help`
`settings => controller/:controller_id/settings`
`settings/console => controller/:controller_id/settings/console`

**Comment by grossmj** [comment]
"Your selected files" should be "Your selected projects".

Screenshot from 2022-07-25 20-42-01

**Review by grossmj — APPROVED** [review]

**Pull request merged**
