### PR TITLE
Fix for The SSL certificate bundle file '*/cacert.pem' could not be found 

### PR DESCRIPTION
**Pull request by piotrpekala7**

### CODE REVIEW

**Comment by piotrpekala7** [comment]
Based on solution proposed in gns3 builds

**Comment by piotrpekala7** [comment]
@ziajka When trying to download modules I have following error:
ERROR: Command errored out with exit status 1:
     command: 'c:\users\administrator\appdata\local\programs\python\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\pip-install-gdsf9rme\\cx-Freeze\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\pip-install-gdsf9rme\\cx-Freeze\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ADMINI~1\AppData\Local\Temp\2\pip-record-awqp36_q\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\ADMINI~1\AppData\Local\Temp\2\pip-install-gdsf9rme\cx-Freeze\
    Complete output (90 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\cx_Freeze
    copying cx_Freeze\common.py -> build\lib.win-amd64-3.7\cx_Freeze
    copying cx_Freeze\dist.py -> build\lib.win-amd64-3.7\cx_Freeze
    copying cx_Freeze\finder.py -> build\lib.win-amd64-3.7\cx_Freeze
    copying cx_Freeze\freezer.py -> build\lib.win-amd64-3.7\cx_Freeze
    copying cx_Freeze\hooks.py -> build\lib.win-amd64-3.7\cx_Freeze
    copying cx_Freeze\macdist.py -> build\lib.win-amd64-3.7\cx_Freeze
    copying cx_Freeze\main.py -> build\lib.win-amd64-3.7\cx_Freeze
    copying cx_Freeze\setupwriter.py -> build\lib.win-amd64-3.7\cx_Freeze
    copying cx_Freeze\windist.py -> build\lib.win-amd64-3.7\cx_Freeze
    copying cx_Freeze\__init__.py -> build\lib.win-amd64-3.7\cx_Freeze
    creating build\lib.win-amd64-3.7\cx_Freeze\initscripts
    copying cx_Freeze\initscripts\Console.py -> build\lib.win-amd64-3.7\cx_Freeze\initscripts
    copying cx_Freeze\initscripts\ConsoleSetLibPath.py -> build\lib.win-amd64-3.7\cx_Freeze\initscripts
    copying cx_Freeze\initscripts\SharedLib.py -> build\lib.win-amd64-3.7\cx_Freeze\initscripts
    copying cx_Freeze\initscripts\SharedLibSource.py -> build\lib.win-amd64-3.7\cx_Freeze\initscripts
    copying cx_Freeze\initscripts\__startup__.py -> build\lib.win-amd64-3.7\cx_Freeze\initscripts
    creating build\lib.win-amd64-3.7\cx_Freeze\samples
    creating build\lib.win-amd64-3.7\cx_Freeze\samples\advanced
    copying cx_Freeze\samples\advanced\advanced_1.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\advanced
    copying cx_Freeze\samples\advanced\advanced_2.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\advanced
    copying cx_Freeze\samples\advanced\setup.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\advanced
    creating build\lib.win-amd64-3.7\cx_Freeze\samples\asmodule
    copying cx_Freeze\samples\asmodule\asmodule.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\asmodule
    copying cx_Freeze\samples\asmodule\setup.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\asmodule
    creating build\lib.win-amd64-3.7\cx_Freeze\samples\matplotlib
    copying cx_Freeze\samples\matplotlib\matplotlib_eg.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\matplotlib
    copying cx_Freeze\samples\matplotlib\setup.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\matplotlib
    creating build\lib.win-amd64-3.7\cx_Freeze\samples\openpyxl
    copying cx_Freeze\samples\openpyxl\setup.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\openpyxl
    copying cx_Freeze\samples\openpyxl\test_openpyxl.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\openpyxl
    creating build\lib.win-amd64-3.7\cx_Freeze\samples\PyQt4
    copying cx_Freeze\samples\PyQt4\PyQt4app.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\PyQt4
    copying cx_Freeze\samples\PyQt4\setup.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\PyQt4
    creating build\lib.win-amd64-3.7\cx_Freeze\samples\PyQt5
    copying cx_Freeze\samples\PyQt5\PyQt5app.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\PyQt5
    copying cx_Freeze\samples\PyQt5\setup.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\PyQt5
    creating build\lib.win-amd64-3.7\cx_Freeze\samples\relimport
    copying cx_Freeze\samples\relimport\relimport.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\relimport
    copying cx_Freeze\samples\relimport\setup.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\relimport
    creating build\lib.win-amd64-3.7\cx_Freeze\samples\service
    copying cx_Freeze\samples\service\Config.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\service
    copying cx_Freeze\samples\service\ServiceHandler.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\service
    copying cx_Freeze\samples\service\setup.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\service
    creating build\lib.win-amd64-3.7\cx_Freeze\samples\simple
    copying cx_Freeze\samples\simple\hello.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\simple
    copying cx_Freeze\samples\simple\setup.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\simple
    creating build\lib.win-amd64-3.7\cx_Freeze\samples\Tkinter
    copying cx_Freeze\samples\Tkinter\setup.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\Tkinter
    copying cx_Freeze\samples\Tkinter\SimpleTkApp.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\Tkinter
    creating build\lib.win-amd64-3.7\cx_Freeze\samples\wx
    copying cx_Freeze\samples\wx\setup.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\wx
    copying cx_Freeze\samples\wx\wxapp.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\wx
    creating build\lib.win-amd64-3.7\cx_Freeze\samples\zope
    copying cx_Freeze\samples\zope\qotd.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\zope
    copying cx_Freeze\samples\zope\setup.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\zope
    running build_ext
    building 'cx_Freeze.util' extension
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\source
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.14.26428\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\administrator\appdata\local\programs\python\python37\include -Ic:\users\administrator\appdata\local\programs\python\python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.14.26428\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.14.26428\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\cppwinrt" /Tcsource/util.c /Fobuild\temp.win-amd64-3.7\Release\source/util.obj
    util.c
    source/util.c(277): warning C4311: 'type cast': pointer truncation from 'HANDLE' to 'long'
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.14.26428\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:c:\users\administrator\appdata\local\programs\python\python37\libs /LIBPATH:c:\users\administrator\appdata\local\programs\python\python37\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.14.26428\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.14.26428\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17134.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17134.0\um\x64" imagehlp.lib Shlwapi.lib /EXPORT:PyInit_util build\temp.win-amd64-3.7\Release\source/util.obj /OUT:build\lib.win-amd64-3.7\cx_Freeze\util.cp37-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.7\Release\source\util.cp37-win_amd64.lib
       Creating library build\temp.win-amd64-3.7\Release\source\util.cp37-win_amd64.lib and object build\temp.win-amd64-3.7\Release\source\util.cp37-win_amd64.exp
    Generating code
    Finished generating code
    creating build\temp.win-amd64-3.7\Release\source\bases
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.14.26428\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\administrator\appdata\local\programs\python\python37\include -Ic:\users\administrator\appdata\local\programs\python\python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.14.26428\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.14.26428\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\cppwinrt" /Tcsource/bases/Console.c /Fobuild\temp.win-amd64-3.7\Release\source/bases/Console.obj
    Console.c
    creating C:\Users\ADMINI~1\AppData\Local\Temp\2\pip-install-gdsf9rme\cx-Freeze\build\lib.win-amd64-3.7\cx_Freeze\bases
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.14.26428\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /MANIFEST:EMBED,ID=1 /LIBPATH:c:\users\administrator\appdata\local\programs\python\python37\libs /LIBPATH:c:\users\administrator\appdata\local\programs\python\python37\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.14.26428\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.14.26428\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17134.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17134.0\um\x64" imagehlp.lib Shlwapi.lib build\temp.win-amd64-3.7\Release\source/bases/Console.obj /OUT:build\lib.win-amd64-3.7\cx_Freeze\bases\Console.exe /MANIFEST
    Generating code
    Finished generating code
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.14.26428\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\administrator\appdata\local\programs\python\python37\include -Ic:\users\administrator\appdata\local\programs\python\python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.14.26428\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.14.26428\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\cppwinrt" /Tcsource/bases/Win32GUI.c /Fobuild\temp.win-amd64-3.7\Release\source/bases/Win32GUI.obj
    Win32GUI.c
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.14.26428\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /MANIFEST:EMBED,ID=1 /LIBPATH:c:\users\administrator\appdata\local\programs\python\python37\libs /LIBPATH:c:\users\administrator\appdata\local\programs\python\python37\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.14.26428\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.14.26428\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17134.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17134.0\um\x64" imagehlp.lib Shlwapi.lib user32.lib build\temp.win-amd64-3.7\Release\source/bases/Win32GUI.obj /OUT:build\lib.win-amd64-3.7\cx_Freeze\bases\Win32GUI.exe /MANIFEST
    Generating code
    Finished generating code
    running build_scripts
    creating build\scripts-3.7
    copying and adjusting cxfreeze -> build\scripts-3.7
    copying and adjusting cxfreeze-quickstart -> build\scripts-3.7
    error: file 'C:\Users\ADMINI~1\AppData\Local\Temp\2\pip-install-gdsf9rme\cx-Freeze\cxfreeze-postinstall' does not exist
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\administrator\appdata\local\programs\python\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\pip-install-gdsf9rme\\cx-Freeze\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\pip-install-gdsf9rme\\cx-Freeze\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ADMINI~1\AppData\Local\Temp\2\pip-record-awqp36_q\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output

**Comment by piotrpekala7** [comment]
Possibly there's a problem with path to this file

**Comment by ziajka** [comment]
We should find cacert.pem dynamically from env: https://github.com/GNS3/gns3-server/commit/57a069b0278ee2e6c16f6b5f2ca8ce5c8888846d (something like this)

**Comment by piotrpekala7** [comment]
While running build.py script I got error that cxFreeze module is missing, however while installing modules from requirements file I got error like that one above

**Comment by piotrpekala7** [comment]
@ziajka any updates here

**Comment by piotrpekala7** [comment]
?

**Comment by piotrpekala7** [comment]
Closed as there's no response

**Pull request closed without merging**
